// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $feed from "./routes/feed.ts";
import * as $index from "./routes/index.tsx";
import * as $micro_slug_ from "./routes/micro/[slug].tsx";
import * as $picture_slug_ from "./routes/picture/[slug].tsx";
import * as $privacy_policy from "./routes/privacy-policy.tsx";
import * as $signin from "./routes/signin.tsx";
import * as $terms_and_conditions from "./routes/terms-and-conditions.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/feed.ts": $feed,
    "./routes/index.tsx": $index,
    "./routes/micro/[slug].tsx": $micro_slug_,
    "./routes/picture/[slug].tsx": $picture_slug_,
    "./routes/privacy-policy.tsx": $privacy_policy,
    "./routes/signin.tsx": $signin,
    "./routes/terms-and-conditions.tsx": $terms_and_conditions,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
